import { Property } from "@/types"

export const dummyProperties: Property[] = [
  {
    id: "1",
    title: "Modern 3-Bedroom Apartment in Kilimani",
    description:
      "Spacious and modern 3-bedroom apartment with stunning city views. Features include a fully equipped kitchen, master ensuite, ample parking, and 24/7 security.",
    price: 85000,
    priceType: "rent",
    location: "Kilimani",
    city: "Nairobi",
    bedrooms: 3,
    bathrooms: 2,
    size: 150,
    type: "apartment",
    images: ["/modern-apartment-living-room.png", "/modern-kitchen.png", "/bedroom-with-city-view.jpg"],
    amenities: ["Parking", "Security", "Gym", "Swimming Pool", "Backup Generator"],
    agent: {
      id: "agent1",
      name: "Jane Wanjiru",
      phone: "+254 712 345 678",
      email: "jane@rentflow360.com",
      avatar: "/professional-woman-diverse.png",
    },
    status: "available",
    views: 245,
    inquiries: 12,
    featured: true,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    verified: true
  },
  {
    id: "2",
    title: "4-Bedroom Villa in Karen",
    description:
      "Luxurious 4-bedroom villa in the prestigious Karen area. Features a large garden, swimming pool, and modern finishes throughout.",
    price: 45000000,
    priceType: "sale",
    location: "Karen",
    city: "Nairobi",
    bedrooms: 4,
    bathrooms: 4,
    size: 350,
    type: "villa",
    images: ["/luxury-villa-exterior.png", "/villa-swimming-pool.jpg", "/luxury-living-room.png"],
    amenities: ["Garden", "Swimming Pool", "Garage", "Security", "Solar Panels"],
    agent: {
      id: "agent2",
      name: "David Omondi",
      phone: "+254 723 456 789",
      email: "david@rentflow360.com",
      avatar: "/professional-man.jpg",
    },
    status: "available",
    views: 567,
    inquiries: 28,
    featured: true,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-18",
    verified: true
  },
  {
    id: "3",
    title: "Cozy 1-Bedroom Studio in Kasarani",
    description:
      "Affordable and cozy studio apartment perfect for young professionals. Close to public transport and shopping centers.",
    price: 25000,
    priceType: "rent",
    location: "Kasarani",
    city: "Nairobi",
    bedrooms: 1,
    bathrooms: 1,
    size: 45,
    type: "studio",
    images: ["/studio-apartment-interior.png", "/compact-kitchen.jpg", "/small-bathroom.png"],
    amenities: ["Parking", "Security", "Water Supply"],
    agent: {
      id: "agent3",
      name: "Mary Njeri",
      phone: "+254 734 567 890",
      email: "mary@rentflow360.com",
      avatar: "/young-woman-agent.jpg",
    },
    status: "available",
    views: 189,
    inquiries: 15,
    featured: false,
    createdAt: "2024-01-12",
    updatedAt: "2024-01-19",
    verified: true
  },
  {
    id: "4",
    title: "2-Bedroom Apartment in Westlands",
    description:
      "Well-maintained 2-bedroom apartment in the heart of Westlands. Walking distance to malls, restaurants, and offices.",
    price: 65000,
    priceType: "rent",
    location: "Westlands",
    city: "Nairobi",
    bedrooms: 2,
    bathrooms: 2,
    size: 100,
    type: "apartment",
    images: ["/apartment-balcony-view.png", "/modern-bedroom.png", "/cozy-dining-nook.png"],
    amenities: ["Parking", "Security", "Elevator", "Backup Generator"],
    agent: {
      id: "agent1",
      name: "Jane Wanjiru",
      phone: "+254 712 345 678",
      email: "jane@rentflow360.com",
      avatar: "/professional-woman-diverse.png",
    },
    status: "available",
    views: 312,
    inquiries: 18,
    featured: true,
    createdAt: "2024-01-08",
    updatedAt: "2024-01-17",
    verified: true
  },
  {
    id: "5",
    title: "Commercial Space in CBD",
    description:
      "Prime commercial space in Nairobi CBD. Ideal for offices, retail, or showroom. High foot traffic area.",
    price: 150000,
    priceType: "rent",
    location: "CBD",
    city: "Nairobi",
    bedrooms: 0,
    bathrooms: 2,
    size: 200,
    type: "commercial",
    images: ["/commercial-office-space.png", "/modern-office-reception.png", "/modern-meeting-room.png"],
    amenities: ["Parking", "Security", "Elevator", "Central AC", "Fiber Internet"],
    agent: {
      id: "agent2",
      name: "David Omondi",
      phone: "+254 723 456 789",
      email: "david@rentflow360.com",
      avatar: "/professional-man.jpg",
    },
    status: "available",
    views: 423,
    inquiries: 31,
    featured: true,
    createdAt: "2024-01-05",
    updatedAt: "2024-01-16",
    verified: true
  },
  {
    id: "6",
    title: "5-Bedroom House in Runda",
    description:
      "Spacious family home in the exclusive Runda estate. Features include a large compound, DSQ, and modern amenities.",
    price: 75000000,
    priceType: "sale",
    location: "Runda",
    city: "Nairobi",
    bedrooms: 5,
    bathrooms: 5,
    size: 450,
    type: "house",
    images: ["/luxury-house-exterior.jpg", "/spacious-living-room.png", "/luxurious-master-suite.png"],
    amenities: ["Garden", "DSQ", "Garage", "Security", "Borehole", "Solar Panels"],
    agent: {
      id: "agent2",
      name: "David Omondi",
      phone: "+254 723 456 789",
      email: "david@rentflow360.com",
      avatar: "/professional-man.jpg",
    },
    status: "available",
    views: 678,
    inquiries: 42,
    featured: true,
    createdAt: "2024-01-03",
    updatedAt: "2024-01-15",
    verified: true
  },
]

enum Role {
  buyer = "buyer",
  seller = "seller",
  renter = "renter",
  admin = "admin",
  agent = "agent"
}

export const dummyUsers = [
  {
    id: "user1",
    name: "John Kamau",
    email: "john@example.com",
    role: "buyer",
    phone: "+254 700 123 456",
    avatar: "/man-profile.png",
    savedProperties: ["1", "2", "4"],
    alerts: [
      { id: "alert1", location: "Kilimani", maxPrice: 100000, bedrooms: 3 },
      { id: "alert2", location: "Westlands", maxPrice: 80000, bedrooms: 2 },
    ],
    reviews: [
      {
        id: "review1",
        propertyId: "1",
        rating: 5,
        comment: "Great apartment, very responsive agent!",
        date: "2024-01-20",
      },
    ],
  },
]

export const dummyAgents = [
  {
    id: "agent1",
    name: "Jane Wanjiru",
    email: "jane@rentflow360.com",
    phone: "+254 712 345 678",
    avatar: "/professional-woman-diverse.png",
    properties: ["1", "4"],
    totalListings: 12,
    activeListings: 8,
    soldListings: 4,
    totalViews: 5432,
    totalInquiries: 234,
  },
  {
    id: "agent2",
    name: "David Omondi",
    email: "david@rentflow360.com",
    phone: "+254 723 456 789",
    avatar: "/professional-man.jpg",
    properties: ["2", "5", "6"],
    totalListings: 18,
    activeListings: 12,
    soldListings: 6,
    totalViews: 8765,
    totalInquiries: 456,
  },
]

export const dummyInquiries = [
  {
    id: "inq1",
    propertyId: "1",
    userId: "user1",
    userName: "John Kamau",
    userEmail: "john@example.com",
    userPhone: "+254 700 123 456",
    message: "I am interested in viewing this property. When is a good time?",
    status: "pending",
    createdAt: "2024-01-21",
  },
  {
    id: "inq2",
    propertyId: "2",
    userId: "user2",
    userName: "Sarah Mwangi",
    userEmail: "sarah@example.com",
    userPhone: "+254 711 234 567",
    message: "Is the price negotiable? I would like to schedule a viewing.",
    status: "responded",
    createdAt: "2024-01-20",
  },
]

export const dummyReports = [
  {
    id: "report1",
    propertyId: "3",
    reportedBy: "user3",
    reason: "Incorrect pricing information",
    description: "The listed price does not match what the agent quoted me.",
    status: "pending",
    createdAt: "2024-01-19",
  },
]

export const dummyAnalytics = {
  totalProperties: 156,
  activeListings: 98,
  totalUsers: 1234,
  totalAgents: 45,
  totalViews: 45678,
  totalInquiries: 2345,
  recentActivity: [
    { date: "2024-01-21", views: 234, inquiries: 12 },
    { date: "2024-01-20", views: 198, inquiries: 15 },
    { date: "2024-01-19", views: 267, inquiries: 18 },
    { date: "2024-01-18", views: 189, inquiries: 9 },
    { date: "2024-01-17", views: 223, inquiries: 14 },
  ],
}
